name: Build Release
on: [create, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Install Deps
        if: runner.os == 'Linux'
        run: sudo apt-get -qq install golang gcc libgl1-mesa-dev xorg-dev
      - name: Install UPX
        if: runner.os == 'macOS'
        run: brew install upx
      - name: Install UPX
        if: runner.os != 'macOS'
        uses: crazy-max/ghaction-upx@v3
        with:
          version: latest
          install-only: true
      - name: Build
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            go build -ldflags "-s -w" -o "keygenerator.run"
          elif [ "$RUNNER_OS" == "Windows" ]; then
            go build -o "keygenerator.exe"
          else
            go build -o "keygenerator.o"
          fi
      - name: Run UPX
        run: upx --best --lzma keygenerator*
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: keygenerator-${{ runner.os }}
          path: keygenerator*
      - name: Create release
        id: create_release
        uses: ncipollo/release-action@v1
        continue-on-error: true
        with:
          allowUpdates: true
          name: Release ${{ github.ref_name }}
          artifacts: keygenerator*
